### ISSUE TITLE
Latest update breaks daily weather output

### ISSUE THREAD

**Issue by badewanne1234** [Rudd-O/homeassistant-meteoswiss#54]
I'm extracting the weather forecast (daily and now als hourly) into sensors since accessing the forecast data has been changed earlier this year.

The daily output is now broken since the update of the meteoswiss integration yesterday. Interestingly, only the daily forecast is broken, but not the freshly introduced hourly forecast.

Here is my config in the configuration.yaml for daily and for hourly:

```
#Meteo Schweiz Wettervorhersage als Attribute
  - trigger:
    - platform: state
      entity_id: weather.wetter_mch
    - platform: homeassistant
      event: start
    - platform: event
      event_type: event_template_reloaded
    action:
      - service: weather.get_forecasts
        data:
          type: daily
        target:
          entity_id: weather.wetter_mch
        response_variable: daily
    sensor:
      - name: Wettervorhersage MCH Taeglich
        unique_id: weather_forecast_mch_daily
        state: "{{ now().isoformat() }}"
        attributes:
          forecast: "{{ daily['weather.wetter_mch'].forecast }}"

#Meteo Schweiz Stündliches Wetter als Attribute
  - trigger:
    - platform: state
      entity_id: weather.wetter_mch
    - platform: homeassistant
      event: start
    - platform: event
      event_type: event_template_reloaded
    action:
      - service: weather.get_forecasts
        data:
          type: hourly
        target:
          entity_id: weather.wetter_mch
        response_variable: hourly
    sensor:
      - name: Wettervorhersage MCH Stuendlich
        unique_id: weather_forecast_mch_hourly
        state: "{{ now().isoformat() }}"
        attributes:
          forecast: "{{ hourly['weather.wetter_mch'].forecast }}"
```
The output of these sensors is as follows:

Daily:
```
friendly_name: Wettervorhersage MCH Taeglich
forecast: [{'datetime': '2024-08-25', 'condition': <Condition.pouring: 'pouring'>, 'temperature': 26.0, 'templow': 15.0, 'precipitation': 13.3}, {'datetime': '2024-08-26', 'condition': <Condition.cloudy: 'cloudy'>, 'temperature': 20.0, 'templow': 15.0, 'precipitation': 0.0}, {'datetime': '2024-08-27', 'condition': <Condition.partly_cloudy: 'partlycloudy'>, 'temperature': 25.0, 'templow': 14.0, 'precipitation': 0.0}, {'datetime': '2024-08-28', 'condition': <Condition.sunny: 'sunny'>, 'temperature': 27.0, 'templow': 16.0, 'precipitation': 0.0}, {'datetime': '2024-08-29', 'condition': <Condition.partly_cloudy: 'partlycloudy'>, 'temperature': 29.0, 'templow': 18.0, 'precipitation': 0.0}, {'datetime': '2024-08-30', 'condition': <Condition.partly_cloudy: 'partlycloudy'>, 'temperature': 25.0, 'templow': 17.0, 'precipitation': 1.5}]
```

Hourly
```
friendly_name: Wettervorhersage MCH Stuendlich
forecast: 
- datetime: '2024-08-25T08:00:00Z'
  temperature: 16.5
  templow: 15.4
  precipitation: 10.4
- datetime: '2024-08-25T09:00:00Z'
  temperature: 15.3
  templow: 14.1
  precipitation: 2.7
```

As you can see, the outputting format is broken for the daily sensor, whilst for hourly its OK.
I have the exact same sensors (daily + hourly) as well for the `met.no` weather integration, and it works as it should for both, daily + hourly in the correct format.
