### ISSUE TITLE
[Question] Pollencount?

### ISSUE THREAD

**Issue by hpmueller1971** [Rudd-O/homeassistant-meteoswiss#56]
MeteoSwiss operates a Pollen-Count-Network, and some of the Data is visible on the Website. Is this information in the API you're using, and if so, could you "just add" those values, or would it require a new API?

**Comment by Rudd-O** [comment]
I would need at a minimum the API URLs and a stations listing.  Right now we only have precipitation and weather station listings (please see `hamsclientfork` source code for that information).

**Comment by Rudd-O** [comment]
I've amended the title, hope that's OK.

**Comment by schmidtfx** [comment]
is there any update? Do you need any help?

**Comment by Rudd-O** [comment]
I do.  I need the data source in question.

**Comment by Agash** [comment]
In case anyone is interested, I made a small pollen card for myself, using the data available from Meteo. You need to change the station abbreviation with the station that is closest to you. The list of the abbreviations is available in the table view [here](https://www.meteoschweiz.admin.ch/service-und-publikationen/applikationen/messwerte-und-messnetze.html#param=messnetz-pollen&table=true&station=PBE). For example, in my configuration, I use the station called PBE for Bern.

It would be nice if we have some sort of integration that does this, as currently with my rest method, the timestamp of the actual data isn't reflected in the timestamp of the sensor in HA. But it's better than nothing :)

Here are the template sensors in my yaml:
```yaml
- platform: rest
  resource: "https://www.meteoschweiz.admin.ch/product/output/measured-values/chartData/betula_hour/chartData.betula_hour.PBE.de.json"
  name: "Birkenpollen (Stündlich)"
  value_template: "{{ value_json.series[0].data | sort(attribute=0, reverse=true) | map(attribute=1) | first | default(0) }}"
  unit_of_measurement: "No/m³"
  scan_interval: 3600
  json_attributes_path: "$.config"
  json_attributes:
    - name
    - timestamp
  icon: mdi:tree-outline

- platform: rest
  resource: "https://www.meteoschweiz.admin.ch/product/output/measured-values/chartData/fagus_hour/chartData.fagus_hour.PBE.de.json"
  name: "Buchenpollen (Stündlich)"
  value_template: "{{ value_json.series[0].data | sort(attribute=0, reverse=true) | map(attribute=1) | first | default(0) }}"
  unit_of_measurement: "No/m³"
  scan_interval: 3600
  json_attributes_path: "$.config"
  json_attributes:
    - name
    - timestamp
  icon: mdi:tree-outline

- platform: rest
  resource: "https://www.meteoschweiz.admin.ch/product/output/measured-values/chartData/quercus_hour/chartData.quercus_hour.PBE.de.json"
  name: "Eichenpollen (Stündlich)"
  value_template: "{{ value_json.series[0].data | sort(attribute=0, reverse=true) | map(attribute=1) | first | default(0) }}"
  unit_of_measurement: "No/m³"
  scan_interval: 3600
  json_attributes_path: "$.config"
  json_attributes:
    - name
    - timestamp
  icon: mdi:tree-outline

- platform: rest
  resource: "https://www.meteoschweiz.admin.ch/product/output/measured-values/chartData/alnus_hour/chartData.alnus_hour.PBE.de.json"
  name: "Erlenpollen (Stündlich)"
  value_template: "{{ value_json.series[0].data | sort(attribute=0, reverse=true) | map(attribute=1) | first | default(0) }}"
  unit_of_measurement: "No/m³"
  scan_interval: 3600
  json_attributes_path: "$.config"
  json_attributes:
    - name
    - timestamp
  icon: mdi:tree-outline

- platform: rest
  resource: "https://www.meteoschweiz.admin.ch/product/output/measured-values/chartData/fraxinus_hour/chartData.fraxinus_hour.PBE.de.json"
  name: "Eschenpollen (Stündlich)"
  value_template: "{{ value_json.series[0].data | sort(attribute=0, reverse=true) | map(attribute=1) | first | default(0) }}"
  unit_of_measurement: "No/m³"
  scan_interval: 3600
  json_attributes_path: "$.config"
  json_attributes:
    - name
    - timestamp
  icon: mdi:sprout-outline

- platform: rest
  resource: "https://www.meteoschweiz.admin.ch/product/output/measured-values/chartData/poaceae_hour/chartData.poaceae_hour.PBE.de.json"
  name: "Gräserpollen (Stündlich)"
  value_template: "{{ value_json.series[0].data | sort(attribute=0, reverse=true) | map(attribute=1) | first | default(0) }}"
  unit_of_measurement: "No/m³"
  scan_interval: 3600
  json_attributes_path: "$.config"
  json_attributes:
    - name
    - timestamp
  icon: mdi:grass

- platform: rest
  resource: "https://www.meteoschweiz.admin.ch/product/output/measured-values/chartData/corylus_hour/chartData.corylus_hour.PBE.de.json"
  name: "Haselpollen (Stündlich)"
  value_template: "{{ value_json.series[0].data | sort(attribute=0, reverse=true) | map(attribute=1) | first | default(0) }}"
  unit_of_measurement: "No/m³"
  scan_interval: 3600
  json_attributes_path: "$.config"
  json_attributes:
    - name
    - timestamp
  icon: mdi:tree-outline
```

And then, here is the card that I'm showing conditionally. All the types of pollen have their recommended values and alert levels adjusted via colors, the levels are what was defined on the Meteo website, per type of pollen. The card itself only shows if there is something above a value of 0 and each type of pollen also does that. This uses mushroom-template cards, so be sure to have that installed.
```yaml
type: conditional
conditions:
  - condition: and
    conditions:
      - condition: state
        entity: sensor.birkenpollen_stundlich
        state_not: unavailable
      - condition: state
        entity: sensor.birkenpollen_stundlich
        state_not: unknown
      - condition: numeric_state
        entity: sensor.birkenpollen_stundlich
        above: 0
      - condition: state
        entity: sensor.buchenpollen_stundlich
        state_not: unavailable
      - condition: state
        entity: sensor.buchenpollen_stundlich
        state_not: unknown
      - condition: numeric_state
        entity: sensor.buchenpollen_stundlich
        above: 0
      - condition: state
        entity: sensor.eichenpollen_stundlich
        state_not: unavailable
      - condition: state
        entity: sensor.eichenpollen_stundlich
        state_not: unknown
      - condition: numeric_state
        entity: sensor.eichenpollen_stundlich
        above: 0
      - condition: state
        entity: sensor.erlenpollen_stundlich
        state_not: unavailable
      - condition: state
        entity: sensor.erlenpollen_stundlich
        state_not: unknown
      - condition: numeric_state
        entity: sensor.erlenpollen_stundlich
        above: 0
      - condition: state
        entity: sensor.eschenpollen_stundlich
        state_not: unavailable
      - condition: state
        entity: sensor.eschenpollen_stundlich
        state_not: unknown
      - condition: numeric_state
        entity: sensor.eschenpollen_stundlich
        above: 0
      - condition: state
        entity: sensor.graserpollen_stundlich
        state_not: unavailable
      - condition: state
        entity: sensor.graserpollen_stundlich
        state_not: unknown
      - condition: numeric_state
        entity: sensor.graserpollen_stundlich
        above: 0
      - condition: state
        entity: sensor.haselpollen_stundlich
        state_not: unavailable
      - condition: state
        entity: sensor.haselpollen_stundlich
        state_not: unknown
      - condition: numeric_state
        entity: sensor.haselpollen_stundlich
        above: 0
card:
  type: vertical-stack
  cards:
    - type: custom:mushroom-title-card
      title: ""
      subtitle: Pollenflug
    - type: grid
      columns: 2
      square: false
      cards:
        - type: conditional
          conditions:
            - condition: state
              entity: sensor.birkenpollen_stundlich
              state_not: unavailable
            - condition: state
              entity: sensor.birkenpollen_stundlich
              state_not: unknown
            - condition: numeric_state
              entity: sensor.birkenpollen_stundlich
              above: 0
          card:
            type: custom:mushroom-template-card
            entity: sensor.birkenpollen_stundlich
            primary: Birke
            secondary: >
              {% set birke = states('sensor.birkenpollen_stundlich') | int %} {%
              if birke <= 10 %}
                schwach ({{birke}} No/m³)
              {% elif birke <= 70 %}
                mässig ({{birke}} No/m³)
              {% elif birke <= 300 %}
                stark ({{birke}} No/m³)
              {% else %}
                sehr stark ({{birke}} No/m³)
              {% endif %}
            icon: mdi:flower
            icon_color: >
              {% set birke = states('sensor.birkenpollen_stundlich') | int %} {%
              if birke <= 10 %}
                #90EE90
              {% elif birke <= 70 %}
                #FFA500
              {% elif birke <= 300 %}
                #FF0000
              {% else %}
                #8B0000
              {% endif %}
            badge_icon: >
              {% set birke = states('sensor.birkenpollen_stundlich') | int %} {%
              if birke > 10 %}
                  mdi:alert-circle
              {% else %}

              {% endif %}
            badge_color: >
              {% set birke = states('sensor.birkenpollen_stundlich') | int %} {%
              if birke > 10 %}
                  red
              {% else %}

              {% endif %}
            layout: horizontal
            multiline_secondary: false
        - type: conditional
          conditions:
            - condition: state
              entity: sensor.buchenpollen_stundlich
              state_not: unavailable
            - condition: state
              entity: sensor.buchenpollen_stundlich
              state_not: unknown
            - condition: numeric_state
              entity: sensor.buchenpollen_stundlich
              above: 0
          card:
            type: custom:mushroom-template-card
            entity: sensor.buchenpollen_stundlich
            primary: Buche
            secondary: >
              {% set buche = states('sensor.buchenpollen_stundlich') | int %} {%
              if buche <= 50 %}
                schwach ({{buche}} No/m³)
              {% elif buche <= 130 %}
                mässig ({{buche}} No/m³)
              {% elif buche <= 400 %}
                stark ({{buche}} No/m³)
              {% else %}
                sehr stark ({{buche}} No/m³)
              {% endif %}
            icon: mdi:tree
            icon_color: >
              {% set buche = states('sensor.buchenpollen_stundlich') | int %} {%
              if buche <= 50 %}
                #90EE90
              {% elif buche <= 130 %}
                #FFA500
              {% elif buche <= 400 %}
                #FF0000
              {% else %}
                #8B0000
              {% endif %}
            badge_icon: >
              {% set buche = states('sensor.buchenpollen_stundlich') | int %} {%
              if buche > 50 %}
                  mdi:alert-circle
              {% else %}

              {% endif %}
            badge_color: >
              {% set buche = states('sensor.buchenpollen_stundlich') | int %} {%
              if buche > 50 %}
                  red
              {% else %}

              {% endif %}
            layout: horizontal
            multiline_secondary: false
        - type: conditional
          conditions:
            - condition: state
              entity: sensor.eichenpollen_stundlich
              state_not: unavailable
            - condition: state
              entity: sensor.eichenpollen_stundlich
              state_not: unknown
            - condition: numeric_state
              entity: sensor.eichenpollen_stundlich
              above: 0
          card:
            type: custom:mushroom-template-card
            entity: sensor.eichenpollen_stundlich
            primary: Eiche
            secondary: >
              {% set eiche = states('sensor.eichenpollen_stundlich') | int %} {%
              if eiche <= 50 %}
                schwach ({{eiche}} No/m³)
              {% elif eiche <= 130 %}
                mässig ({{eiche}} No/m³)
              {% elif eiche <= 400 %}
                stark ({{eiche}} No/m³)
              {% else %}
                sehr stark ({{eiche}} No/m³)
              {% endif %}
            icon: mdi:tree-outline
            icon_color: >
              {% set eiche = states('sensor.eichenpollen_stundlich') | int %} {%
              if eiche <= 50 %}
                #90EE90
              {% elif eiche <= 130 %}
                #FFA500
              {% elif eiche <= 400 %}
                #FF0000
              {% else %}
                #8B0000
              {% endif %}
            badge_icon: >
              {% set eiche = states('sensor.eichenpollen_stundlich') | int %} {%
              if eiche > 50 %}
                  mdi:alert-circle
              {% else %}

              {% endif %}
            badge_color: >
              {% set eiche = states('sensor.eichenpollen_stundlich') | int %} {%
              if eiche > 50 %}
                  red
              {% else %}

              {% endif %}
            layout: horizontal
            multiline_secondary: false
        - type: conditional
          conditions:
            - condition: state
              entity: sensor.erlenpollen_stundlich
              state_not: unavailable
            - condition: state
              entity: sensor.erlenpollen_stundlich
              state_not: unknown
            - condition: numeric_state
              entity: sensor.erlenpollen_stundlich
              above: 0
          card:
            type: custom:mushroom-template-card
            entity: sensor.erlenpollen_stundlich
            primary: Erle
            secondary: >
              {% set erle = states('sensor.erlenpollen_stundlich') | int %} {%
              if erle <= 10 %}
                schwach ({{erle}} No/m³)
              {% elif erle <= 70 %}
                mässig ({{erle}} No/m³)
              {% elif erle <= 250 %}
                stark ({{erle}} No/m³)
              {% else %}
                sehr stark ({{erle}} No/m³)
              {% endif %}
            icon: mdi:leaf
            icon_color: >
              {% set erle = states('sensor.erlenpollen_stundlich') | int %} {%
              if erle <= 10 %}
                #90EE90
              {% elif erle <= 70 %}
                #FFA500
              {% elif erle <= 250 %}
                #FF0000
              {% else %}
                #8B0000
              {% endif %}
            badge_icon: >
              {% set erle = states('sensor.erlenpollen_stundlich') | int %} {%
              if erle > 10 %}
                  mdi:alert-circle
              {% else %}

              {% endif %}
            badge_color: >
              {% set erle = states('sensor.erlenpollen_stundlich') | int %} {%
              if erle > 10 %}
                  red
              {% else %}

              {% endif %}
            layout: horizontal
            multiline_secondary: false
        - type: conditional
          conditions:
            - condition: state
              entity: sensor.eschenpollen_stundlich
              state_not: unavailable
            - condition: state
              entity: sensor.eschenpollen_stundlich
              state_not: unknown
            - condition: numeric_state
              entity: sensor.eschenpollen_stundlich
              above: 0
          card:
            type: custom:mushroom-template-card
            entity: sensor.eschenpollen_stundlich
            primary: Esche
            secondary: >
              {% set esche = states('sensor.eschenpollen_stundlich') | int %} {%
              if esche <= 10 %}
                schwach ({{esche}} No/m³)
              {% elif esche <= 100 %}
                mässig ({{esche}} No/m³)
              {% elif esche <= 350 %}
                stark ({{esche}} No/m³)
              {% else %}
                sehr stark ({{esche}} No/m³)
              {% endif %}
            icon: mdi:leaf-maple
            icon_color: >
              {% set esche = states('sensor.eschenpollen_stundlich') | int %} {%
              if esche <= 10 %}
                #90EE90
              {% elif esche <= 100 %}
                #FFA500
              {% elif esche <= 350 %}
                #FF0000
              {% else %}
                #8B0000
              {% endif %}
            badge_icon: >
              {% set esche = states('sensor.eschenpollen_stundlich') | int %} {%
              if esche > 10 %}
                  mdi:alert-circle
              {% else %}

              {% endif %}
            badge_color: >
              {% set esche = states('sensor.eschenpollen_stundlich') | int %} {%
              if esche > 10 %}
                  red
              {% else %}

              {% endif %}
            layout: horizontal
            multiline_secondary: false
        - type: conditional
          conditions:
            - condition: state
              entity: sensor.graserpollen_stundlich
              state_not: unavailable
            - condition: state
              entity: sensor.graserpollen_stundlich
              state_not: unknown
            - condition: numeric_state
              entity: sensor.graserpollen_stundlich
              above: 0
          card:
            type: custom:mushroom-template-card
            entity: sensor.graserpollen_stundlich
            primary: Gräser
            secondary: >
              {% set graeser = states('sensor.graserpollen_stundlich') | int %}
              {% if graeser <= 20 %}
                schwach ({{graeser}} No/m³)
              {% elif graeser <= 50 %}
                mässig ({{graeser}} No/m³)
              {% elif graeser <= 150 %}
                stark ({{graeser}} No/m³)
              {% else %}
                sehr stark ({{graeser}} No/m³)
              {% endif %}
            icon: mdi:grass
            icon_color: >
              {% set graeser = states('sensor.graserpollen_stundlich') | int %}
              {% if graeser <= 20 %}
                #90EE90
              {% elif graeser <= 50 %}
                #FFA500
              {% elif graeser <= 150 %}
                #FF0000
              {% else %}
                #8B0000
              {% endif %}
            badge_icon: >
              {% set graeser = states('sensor.graserpollen_stundlich') | int %}
              {% if graeser > 20 %}
                  mdi:alert-circle
              {% else %}

              {% endif %}
            badge_color: >
              {% set graeser = states('sensor.graserpollen_stundlich') | int %}
              {% if graeser > 20 %}
                  red
              {% else %}

              {% endif %}
            layout: horizontal
            multiline_secondary: false
        - type: conditional
          conditions:
            - condition: state
              entity: sensor.haselpollen_stundlich
              state_not: unavailable
            - condition: state
              entity: sensor.haselpollen_stundlich
              state_not: unknown
            - condition: numeric_state
              entity: sensor.haselpollen_stundlich
              above: 0
          card:
            type: custom:mushroom-template-card
            entity: sensor.haselpollen_stundlich
            primary: Hasel
            secondary: >
              {% set hasel = states('sensor.haselpollen_stundlich') | int %} {%
              if hasel <= 10 %}
                schwach ({{hasel}} No/m³)
              {% elif hasel <= 70 %}
                mässig ({{hasel}} No/m³)
              {% elif hasel <= 250 %}
                stark ({{hasel}} No/m³)
              {% else %}
                sehr stark ({{hasel}} No/m³)
              {% endif %}
            icon: mdi:pine-tree
            icon_color: >
              {% set hasel = states('sensor.haselpollen_stundlich') | int %} {%
              if hasel <= 10 %}
                #90EE90
              {% elif hasel <= 70 %}
                #FFA500
              {% elif hasel <= 250 %}
                #FF0000
              {% else %} #8B0000 {% endif %}
            badge_icon: >
              {% set hasel = states('sensor.haselpollen_stundlich') | int %} {%
              if hasel > 10 %}
                  mdi:alert-circle
              {% else %}
                  
              {% endif %}              
            badge_color: >
              {% set hasel = states('sensor.haselpollen_stundlich') | int %} {%
              if hasel > 10 %}
                  red
              {% else %}

              {% endif %}
            layout: horizontal
            multiline_secondary: false
```
