### ISSUE TITLE
current weather and forecast for Winterthur (WIN)?

### ISSUE THREAD

**Issue by schneich** [Rudd-O/homeassistant-meteoswiss#66]
I use the meteoswiss integration now for some time. I life in Winterthur, so the next real time weather station is at the airport in Zurich. In Winterthur, there is only an automated rain measurement station.

Is there a way to get the local weather data for Winterthur, as I can get the data within the official MeteoSwiss App on my phone?

I have just re-installed the integration:

![grafik](https://github.com/user-attachments/assets/9e38f34d-29d2-40e2-89cb-bacafd72e698)

![grafik](https://github.com/user-attachments/assets/8e2daec9-bccf-40e5-9510-c647a681c2b5)

This results in the data from the airport being available, but all sensors for Winterthur are _unavailable_.

**Comment by schneich** [comment]
Anybody?

I am very sure that I had some weather data for Winterthur, as all the sensors are created within HomeAssisstant. I even had an automation, which performed some action based on the weather conditions in Winterthur. How do I get that information back?

**Comment by R0bin83** [comment]
Hey @schneich,  
Following my learnings from the past few weeks, in which I got a bit into Swissmeteo and their data:  

When you go to: https://www.meteoschweiz.admin.ch/lokalprognose/winterthur/8400.html#forecast-tab=detail-view  
There is a section "Lokalprognose," and within you find a kind of current weather with a certainty score. That's what you get in the app when selecting "Winterthur." On the same page, all the way down, you find the real current readings from a weather station. In the case of Winterthur, it's - as you mentioned - Zürich Kloten.  

The data you get from the integration are the real readings from the closest station. In the app, they use their (forecast) models across CH to show the calculated values for every small town you may know.  
Basically, what you see here: https://www.meteoschweiz.admin.ch/service-und-publikationen/applikationen/temperatur.html  
The further you scroll into the future, the more uncertainty is added to the values displayed.  

Summarized, all values you find in the app for all locations which have no weather station are short-term forecast data based on the current readings of all the stations.  

Now you need to decide whether you want the real readings or the short-term forecast data.  
If you can live with the temperature data from the Zurich station: perfect.  
If not, you need to get the data from the app API, which is more of a grey zone at the moment.  

In HA (short):  
Get the data via a REST sensor:  

Something like this:  
```yaml
- platform: rest
  name: MeteoSwiss API Data
  resource: https://app-prod-ws.meteoswiss-app.ch/v2/plzDetail?plz=8400
  method: GET
  headers:
    User-Agent: HomeAssistant
    Accept-Language: de-CH
  json_attributes:
    - currentWeather
  scan_interval: 600
```

Please don't call it more often than this.  

And read the temperature with a template sensor:  
```yaml
- sensor:
    - name: "MeteoSchweiz Temperatur"
      state: >
        {{ state_attr('sensor.meteoswiss_api_data', 'currentWeather')['temperature'] }}
      unit_of_measurement: "°C"
      device_class: temperature
```
